version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./ari:/var/www
    volumes_from:
      - data
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./ari:/var/www
    links:
      - db
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
    volumes_from:
      - data
  db:
    image: mysql:5.6
    environment:
      - "MYSQL_ROOT_PASSWORD=123123"
      - "MYSQL_DATABASE=blog"
    ports:
      - "33061:3306"

  data:
    build:
      context: ./
      dockerfile: data.dockerfile
    volumes:
    - ./ari:/var/www
    privileged: true
